.\"                              hey, Emacs:   -*- nroff -*-
.\" multispeech is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; see the file COPYING.  If not, write to
.\" the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
.\"
.TH MULTISPEECH.CONF 5 "March 2, 2010"
.\" Please update the above date whenever this man page is modified.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins (default)
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
multispeech.conf \- Multispeech configuration file
.SH DESCRIPTION
On startup \fBmultispeech\fP expects to find it's configuration
in \fI<sysconfdir>/multispeech.conf\fP and \fI~/.multispeechrc\fP.
The user settings provided by \fI~/.multispeechrc\fP
always take precedence over the system\-wide ones
from \fI<sysconfdir>/multispeech.conf\fP. And all these settings in turn
can be overridden by an extra configuration file specified via the
command line. Some configuration options are mandatory, so at least
one of these files must exist.
.SH "SYNTAX"
The syntax is quite simple.
.PP
Lines started from the \(oq#\(cq character are treated as comments.
Blank lines are ignored. Each option entry looks like follows:
.PP
keyword = value
.PP
Case is significant.
.PP
All options are logically grouped by sections.
Each section is started by its name in square brackets on a separate
line.
.SH "EMACSPEAK INTERACTION CONTROL OPTIONS"
These options are grouped in the section named \(oqfrontend\(cq. These
options are as follows:
.TP
.B charset
.br
Input charset should be specified by its name. Available names
can be found in \fI/usr/share/i18n/SUPPORTED\fP or wherever else
it is on your system. By default this option is not set
so current locale setting is used.
.TP
.B native_notation
.br
Enable native voice control embedded commands.
.TP
.B dtk_notation
.br
Enable DECtalk voice control embedded commands.
.PP
These two options control inline parameters parsing. In the default
state only native notation is enabled, so \fBmultispeech\fP behaves as
it used to and accepts only special inline commands formed by
\fBemacspeak\fP. When dtk notation is enabled, \fBmultispeech\fP
recognizes DECtalk inline commands and tries to emulate some subset of
the DECtalk voice control capabilities. Use the word \(oqyes\(cq or
\(oqon\(cq to enable and the word \(oqno\(cq or \(oqoff\(cq to disable
the option. Nothing prevents to keep both options enabled
simultaneously. In this case DECtalk inline commands will be accepted
as well as the native ones. If both options are disabled, then inline
commands detection and parsing will not be performed at all.
.SH "SSIP RELATED OPTIONS"
Section \(oqssip\(cq contains options that affect \fBmultispeech\fP
behaviour as an SSIP server.
.TP
.B port
.br
TCP port on which SSIP client connections will be accepted. By default
port 6560 is used.
.TP
.B sounds
.br
Path to the directory where sound icons are stored.
.TP
.B split_multiline_messages
.br
When this option is set, multiline messages sent by command
\(oqspeak\(cq are processed and synthisized line by line, that
provides more flexibility in the sense of language detection and
resuming context control, but may cause some additional speech
articulation. Of course, message itself remains atomic in the protocol
terms. By default all lines of the multiline message are concatenated
and processed as one continuous text chunk.
.SH "GENERAL AUDIO OUTPUT CONTROL OPTIONS"
Section name is \(oqaudio\(cq. It contains following options:
.TP
.B device
.br
Default device for all audio output (speech, sounds and tones).
If it is not specified explicitly, then system default will be used.
The DSP device specifications (such as \(oq/dev/dsp\(cq)
are allowed here as well as the ALSA ones.
.TP
.B volume
.br
Volume level applied to all audio output in general.
It should be in the range of (0.0..1.0]. When this option is not
specified the default value 0.8 is used.
.TP
.B latency
.br
Audio output latency in seconds. Default value 0.0 implies
that reasonable latency will be chosen automatically.
Normally this option should not be set up explicitly.
Do it only if you are pretty unsatisfied by the automatic choice.
.SH "SOUNDS PLAYING CONTROL OPTIONS"
Section name is \(oqsounds\(cq. It contains several options that
affect sound file playing capability:
.TP
.B device
.br
Sound files playing device. This setting overwrites general default
and allows to play sound files on a separate audio device.
The DSP device specifications (such as \(oq/dev/dsp\(cq)
are accepted here as well as the ALSA ones.
.TP
.B volume
.br
Relative volume level for sound files playing. It is 1.0
by default.
.TP
.B asynchronous
.br
This option enables or disables to play sound files
simultaneously with other audio activities, such as
speech and tone signals producing. It is enabled by default.
Use the word \(oqyes\(cq or \(oqon\(cq to enable and the word
\(oqno\(cq or \(oqoff\(cq to disable.
.SH "TONE SIGNALS PRODUCING CONTROL OPTIONS"
Section name is \(oqtones\(cq. It consists of the following options:
.TP
.B device
.br
Tones producing device. This setting overwrites general default
and allows to use a separate device for tone signals.
The DSP device specifications (such as \(oq/dev/dsp\(cq)
are accepted here as well as the ALSA ones.
.TP
.B volume
.br
Relative volume level for tone signals producing. It is 1.0
by default.
.TP
.B sampling
.br
Sampling frequency for generated tone signals. It is 44100
by default.
.TP
.B asynchronous
.br
This option enables or disables to produce tone signals
simultaneously with other audio activities, such as
speech and sound files playing. It is enabled by default.
Use the word \(oqyes\(cq or \(oqon\(cq to enable and the word
\(oqno\(cq or \(oqoff\(cq to disable.
.SH "GENERAL SPEECH CONTROL OPTIONS"
Section name is \(oqspeech\(cq. These options affect speech output in
general:
.TP
.B device
.br
Speech output device. This setting overwrites general default
and allows to produce speech on a separate audio device.
The DSP device specifications (such as \(oq/dev/dsp\(cq)
are accepted here as well as the ALSA ones.
.TP
.B volume
.br
Relative volume level for speech output. It is 1.0 by default.
.TP
.B pitch
.br
Voice pitch adjustment relative to it's normal level.
It is 1.0 by default. Greater value causes higher pitch.
.TP
.B rate
.br
Relative speech rate for all voices. It is 1.0 by default.
Higher value causes quicker speech.
.TP
.B char.pitch
.br
Relative voice pitch control applied to the single
letters pronunciation. By default 1.0 is suggested.
.TP
.B char.rate
.br
Relative speech rate control applied to the single
letters pronunciation. By default 1.0 is suggested.
.TP
.B caps_factor
.br
Voice pitch factor for capital letters. By default it is 1.2
so capital letters are pronounced by slightly higher pitch.
.TP
.B language
.br
Define speech synthesis language. Allowed values are: \(oqen\(cq
for English, \(oqru\(cq for Russian or \(oqautodetect\(cq for
automatic detection from the text nature. By default language is
autodetected.
.TP
.B en.engine
.br
English TTS engine. This option has no default. If it is not set then
English speech output will be unavailable in Multispeech. Reasonable
alternatives are as follows:
.br
\fBfreephone\fP \- English speech with Freephone and Mbrola voice
\(oqen1\(cq;
.br
\fBespeak\fP \- English speech with Espeak TTS engine;
.br
\fBuser\fP \- user defined TTS engine.
.TP
.B ru.engine
.br
Russian TTS engine. This option has no default. If it is not set then
Russian speech output will be unavailable in Multispeech. Reasonable
alternatives are as follows:
.br
\fBru_tts\fP \- Russian speech with Ru_tts speech synthesizer;
.br
\fBespeak\fP \- Russian speech with Espeak TTS engine;
.br
\fBuser\fP \- user defined TTS engine.
.SH "VOICE RELATED SPEECH CONTROL OPTIONS"
There is a separate section for each supported voice named by the
unique voice identifier. The following names are recognized:
\(oqmbrola-en1\(cq, \(oqmbrola-us1\(cq, \(oqmbrola-us2\(cq,
\(oqmbrola-us3\(cq, \(oqespeak-default\(cq, \(oqespeak-ru\(cq.
These sections contain quite the same collection of speech control
options for a specific voice.
.PP
Each voice specific section consists of the following options:
.TP
.B voice_name
.br
Conventional voice name that will be used, for instance, in SSIP
communications instead of default identifier.
.TP
.B volume
.br
Specific voice loudness relatively to the general speech volume
level. It is 1.0 by default.
.TP
.B pitch
.br
Specific voice pitch adjustment relative to it's normal level.
It is 1.0 by default. Greater value causes higher pitch.
.TP
.B rate
.br
Relative speech rate for specific voice. It is 1.0 by default.
Higher value causes quicker speech.
.SH "MBROLA RELATED OPTIONS"
Section named \(oqmbrola\(cq contains some options affecting
\fBmultispeech\fP interaction with \fBmbrola\fP speech engine:
.TP
.B executable
.br
Path to the Mbrola executable. If only program name is specified
(as it is by default) then environment variable \fBPATH\fP
will be examined and all paths mentioned there will be searched.
.TP
.B voices
.br
Path to the directory where Mbrola voice files are stored.
By default \(oq<datadir>/mbrola-voices\(cq is suggested.
.SH "FREEPHONE RELATED OPTIONS"
Section named \(oqfreephone\(cq is devoted to \fBfreephone\fP speech
backend. Here are the following options:
.TP
.B executable
.br
Path to the Freephone executable. If only program name is specified
(as it is by default) then environment variable \fBPATH\fP
will be examined and all paths mentioned there will be searched.
.TP
.B lexicon
.br
Path to the lexical database. By default
\(oq<datadir>/freespeech/enlex.db\(cq is suggested.
.SH "RU TTS RELATED OPTIONS"
Section named \(oqru_tts\(cq consists of options that control
\fBmultispeech\fP interaction with \fBru_tts\fP speech synthesizer:
.TP
.B executable
.br
Path to the Ru_tts executable. If only program name is specified
(as it is by default) then environment variable \fBPATH\fP
will be examined and all paths mentioned there will be searched.
.TP
.B lexicon
.br
Path to the lexical database. By default
\(oq<datadir>/freespeech/rulex.db\(cq is suggested.
.TP
.B log
.br
Optional file to collect unknown words. This file must be writable
for the Multispeech user. The collected data can be used later
to improve lexical database. No such file is suggested by default
so unknown words are not stored.
.PP
Since this backend has it's own voice, all voice related options are
also allowed here.
.SH "ESPEAK RELATED OPTIONS"
Interaction with \fBespeak\fP TTS engine is controlled by the options
grouped in section \(oqespeak\(cq:
.TP
.B executable
.br
Path to the Espeak executable. If only program name is specified
(as it is by default) then environment variable \fBPATH\fP
will be examined and all paths mentioned there will be searched.
.TP
.B en.voice
.br
English voice specification. By default \(oqespeak-default\(cq is
suggested. All known \fBespeak\fP and \fBmbrola\fP voices can be used
here.
.TP
.B ru.voice
.br
Russian voice specification. By default \(oqespeak-ru\(cq is
suggested.
.SH "USER DEFINED TTS BACKEND OPTIONS"
The section name is \(oquser\(cq. The following options are grouped
here:
.TP
.B command
.br
Shell command to perform TTS transformation. This command
must accept text on the standard input and produce sound
stream on the standard output. It should be a simple command,
pipes or other shell complications are not allowed here,
but command line arguments may be specified. Moreover, there are
several special keywords recognized by Multispeech and replaced
by actual values internally just before execution. This mechanism
allows Multispeech to pass current speech parameters to the TTS
engine. These keywords are as follows:
.PP
\fB%lang\fP \- replaced by the language id string;
.br
\fB%voice\fP \- replaced by conventional voice name;
.br
\fB%pitch\fP \- replaced by relative voice pitch value;
.br
\fB%rate\fP \- replaced by relative speech rate value;
.br
\fB%freq\fP \- replaced by the sampling frequency value.
.PP
The last keyword is replaced only when freq_control is enabled
(see below).
.TP
.B freq_control
.br
Set this option to \(oqyes\(cq if TTS engine accepts sampling frequency
specification (as \fBmbrola\fP does, for instance) and you wish
to make use of this capability. This option allows \(oq%freq\(cq
keyword replacement in command line. Leave commented out if unsure.
.SH "USER VOICE DEFINITION SECTIONS"
It is assumed that the user defined TTS engine has separate voice for
each supported language, so there are separate sections named
\(oquser-en\(cq for English and \(oquser-ru\(cq for Russian voice. All
these sections contain quite the same set of options.
.TP
.B format
.br
Produced sound stream sample format. The following values
are allowed here:
.PP
\fBs8\fP \- signed 8 bits;
.br
\fBu8\fP \- unsigned 8 bits;
.br
\fBs16\fP \- signed 16 bits.
.PP
Leave this option commented out if sound stream is produced
in a format that can be detected automatically, such as wave file
for instance.
.TP
.B sampling
.br
Produced sound stream sampling frequency in Hz. Assumed 22050
by default. This option is ignored when sound stream format
is autodetected.
.TP
.B stereo
.br
Set to \(oqyes\(cq if produced sound stream is stereo. By default it is
assumed mono. This option is ignored when sound stream format is
autodetected.
.TP
.B charset
.br
Character set in which the TTS engine accepts  it's input.
Available charset names can be found in \fI/usr/share/i18n/SUPPORTED\fP
or wherever else it is on your system. By default this option
is not set so current locale setting is used.
.TP
.B acceleration
.br
Apply additional speech tempo acceleration. Speech rate
will be changed by specified difference in percents
compared to the original tempo. Positive values cause
speech acceleration while the negative ones actually imply
slowing it down. Default value is 0 so no additional
tempo change is applied.
.TP
.B voice_name
.br
Conventional voice name that will be used, for instance, in SSIP
communications instead of default identifier.
.TP
.B dialect
.br
Language dialect identification for use in SSIP communications. By
default \(oqnone\(cq is assumed.
.TP
.B volume
.br
Relative volume level for the voice. By default 1.0 is assumed.
.TP
.B rate
.br
Relative speech rate for the voice. By default 1.0 is assumed.
.TP
.B pitch
.br
Relative voice pitch. By default 1.0 is assumed.
.SH "SEE ALSO"
.BR espeak(1),
.BR freephone(1),
.BR mbrola(1),
.BR multispeech(1),
.BR ru_tts(1).
.SH AUTHOR
Igor B. Poretsky <poretsky@mlbox.ru>.
