#!/bin/sh

if [ $3 ]
then VOLUME=$3
else VOLUME=0.8
fi
if [ $4 ]
then FREQUENCY=$4
else FREQUENCY=10000
fi

if [ -s /etc/sound_48Khz_only ]
then exec sox -t raw -s -b -r $FREQUENCY -c 1 -v $VOLUME - -t ossdsp -r 48000 -c 2 -w $DSP_DEVICE
else exec sox -t raw -s -b -r $FREQUENCY -c 1 -v $VOLUME - -t ossdsp -c 2 -w $DSP_DEVICE
fi
