#!/bin/sh
# emacspeak - execute emacs with speech enhancements
#$Id: emacspeak.def,v 8.560 1998/10/11 19:46:58 raman Exp
#raman $
#
# Modified by Igor B. Poretsky
# for using with Mbrola.
#
EMACS_UNIBYTE=1
DTK_TCL=/usr/local/lib/multispeech/speech_server
EMACSPEAK_DIR=/usr/share/emacs/site-lisp/emacspeak
export EMACS_UNIBYTE
export DTK_TCL
emacs -q -l $EMACSPEAK_DIR/emacspeak-setup.el -l $EMACSPEAK_DIR/multilingual-server.el -l $HOME/.emacs $*
