#!/bin/sh
export LLIAPHON_NOARCH="/usr/local/share/lliaphon"
MYUID=`id -u`
pkill -u $MYUID -KILL lliaphon-client

if [ -ne $(pgrep -u $MYUID lliaphon) ]; then
    lliaphonctl start
fi

exec lliaphon-client | mbrola -t $1 -f $2 -v $3 -l $4 -I $LLIAPHON_NOARCH/initfile.lia -e /usr/local/share/mbrola/voices/fr4 - -A
