name: Create release
on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write

    steps:
      - name: Clone
        uses: actions/checkout@v5

      - name: Install dependencies
        run: |
          sudo apt -q -y update
          sudo apt -q -y install autoconf-archive libbobcat-dev libboost-filesystem-dev libboost-iostreams-dev libboost-locale-dev libboost-program-options-dev libboost-regex-dev libboost-thread-dev libportaudiocpp0 libpulse-dev libsndfile1-dev libsoundtouch-dev libspeechd-dev portaudio19-dev

      - name: Build distribution
        run: |
          autoreconf -if
          ./configure
          make dist dist-xz

      - name: Publish release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            multispeech-*.tar.*
